unstable_features = true
binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
combine_control_expr = false
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
force_multiline_blocks = false
format_macro_matchers = true
format_macro_bodies = true
format_strings = false
tab_spaces = 4
imports_indent = "Visual"
imports_layout = "Mixed"
indent_style = "Block"
match_arm_blocks = true
match_block_trailing_comma = true
trailing_comma = "Vertical"
merge_derives = true
imports_granularity = "Preserve"
newline_style = "Unix"
overflow_delimited_expr = false
reorder_impl_items = false
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_lit_single_line = true
trailing_semicolon = false
type_punctuation_density = "Wide"
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true
max_width = 100
fn_args_layout = "Compressed"
